name: flutter_opencv_dlib
description: DLib
version: 0.0.1
homepage: https://github.com/alnitak/flutter_opencv_dlib

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

  # https://pub.dev/packages/ffi
  ffi: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.bavagnoli.flutter_opencv_dlib
        pluginClass: FlutterOpencvDlibPlugin
      ios:
        pluginClass: FlutterOpencvDlibPlugin
      linux:
        pluginClass: FlutterOpencvDlibPlugin
      macos:
        pluginClass: FlutterOpencvDlibPlugin
      windows:
        pluginClass: FlutterOpencvDlibPluginCApi

  assets:
    - assets/
